# wrangler.toml
# Title: Wrangler Configuration
# Description: Config for Cloudflare Pages or Workers deployment of this Next.js export.

name = "bikram-portfolio"
compatibility_date = "2025-02-11"

[build]
command = "pnpm build && pnpm export"

[site]
bucket = "./out"
entry-point = "."